### ISSUE TITLE
Change voting setting client 

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/pattern-subdao-plugin#3]
# ToDo

- [ ] Create changeVotingSetting.ts under scripts/src/client 
- [ ] Create function that removes a list of addresses from approvers of multisig plugin
       Check if approver is listed under approvers if not throw error
- [ ] Create function that removes a list of addresses from approvers of token voting plugin
       Check if approver is listed under approvers 
- [ ] Create function that adds a list of addresses to approvers of to multisig plugin
        Check if address is already an approver, if so throw error 
- [ ] Create function that changes token weight of an address in token voting plugin
        Check if action is possible before sending to network
- [ ] Create function that adds a list of addresses to approvers of token voting plugin
        Check if address is already an approver, if so throw error 
- [ ] Get args from terminal when running the changeVotingSetting.ts file and call the appropriate action (check [installSubDAOPlugin.ts](https://github.com/Microflow-xyz/pattern-subdao-plugin/blob/main/scripts/src/client/installSubDAOPlugin.ts) for example 
- [ ] Add a section to readme for how to change voting setting and explain how to use changeVotingSetting.ts
- [ ] Create common.ts under scripts/src/client then move all duplicate code inside changeVotingSetting.ts, newDao.ts, and installSubDAOPlugin.ts to it
